[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "rsbio-seq"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version", "readme", "description", "authors"]
keywords = ["bioinformatics", "genomics"]
license = { file = "LICENSE" }

[project.urls]
Documentation = "https://github.com/anuradhawick/rsbio-seq/"
"Bug Tracker" = "https://github.com/anuradhawick/rsbio-seq/issues"
"Source Code" = "https://github.com/anuradhawick/rsbio-seq/"

[tool.maturin]
features = ["pyo3/extension-module"]
